services:
  fastapi:
    public: true
    build: .
    replicas: 1
    environment:
      - REDIS_URI=redis://redistogo:dc51bb4e249163e2d22c50cb1dfbbe01@barb.redistogo.com:10268/ #change this REDIS_URI get it from redistogo.com
      - PYTHON_ENV=prod
      - CACHE_EXPIRATION=180
    ports:
      - 8080
    resources:
      requests:
        cpu: 500m
        memory: 1500Mi
      limits:
        cpu: 1000m
        memory: 3000Mi
